create table customer (custid int primary key ,custname varchar(100),custaddress varchar(100))
insert into customer values(1,'ram','Nagpur')
insert into customer values(2,'kiram','Nagpur')
insert into customer values(3,'pooja','Wardha')
insert into customer values(4,'kiran','Amravti')
insert into customer values(5,'Ramesh','Nagpur')
insert into customer values(6,'subhod','Nagpur')
insert into customer values(7,'priya','Nagpur')
insert into customer values(44,'pranay','Pune')
insert into customer values(8,'prjwal','Nagpur')
insert into customer values(9,'ram','Nagpur')
select * from customer