create table product (productno int identity ,productname varchar(100),Amount int)
insert into product values('Book',400)
insert into product values('pen',5500)
insert into product values('bottole',800)
insert into product values('Tipen',1400)
insert into product values('watch',52400)
insert into product values('bookdictionary',500)
insert into product values('lock',700)
select productno,productname,Amount from product order by LEN(productname)